theme: jekyll-theme-minimal
title: ğŸ§‘ğŸ» Michael Zhao
description:
  <a href="https://mzhao8.github.io/links/">ğŸ”—Links</a>
  <br>
  <a href="https://mzhao8.github.io/ideas/">ğŸ’¡Ideas</a>
  <br>
  <a href="https://mzhao8.github.io/books/">ğŸ“šBooks</a>
  <br>
  <a href="https://mzhao8.github.io/quotes/">ğŸ¤Quotes</a>
  <br>
  <a href="https://mzhao8.github.io/essays/">âœğŸ»Essays</a>
  <br>
  <a href="https://mail.google.com/mail/u/0/?view=cm&fs=1&tf=1&to=mzhao8.github@gmail.com" rel="noopener noreferrer" target="_blank">ğŸ“®mail</a>
  <br>
  <a href="https://www.linkedin.com/in/michael-zhao-58932399/" rel="noopener noreferrer" target="_blank">ğŸ‘”Linkedin</a>
google_analytics: UA-186079228-1
